import sys
import re

import mwparserfromhell


DEFAULT_NORMALIZE = True
DEFAULT_COLLAPSE = True
DEFAULT_KEEP_TEMPLATE_PARAMS = False
DEFAULT_SKIP_STYLE_TAGS = False
MEDIA_PREFIXES = ("file", "image", "media", "hình", "phương tiện", "tập tin")
CATEGORY_PREFIXES = ("category", "thể loại")
REMOVED_TAGS = {"ref", "table"}
REF_RE = re.compile(
    r"<ref\b[^>]*?/>|<ref\b[^>]*?>.*?</ref\s*>", flags=re.IGNORECASE | re.DOTALL
)
REF_TAG_RE = re.compile(r"</?ref\b[^>]*>", flags=re.IGNORECASE)
MALFORMED_REF_LINE_RE = re.compile(
    r"<ref\b[^\n>]*$", flags=re.IGNORECASE | re.MULTILINE
)
REFERENCES_TAG_RE = re.compile(r"</?references\b[^>]*>", flags=re.IGNORECASE)
MAGIC_WORD_RE = re.compile(r"__[A-Z]+__")
LEADING_COMMENT_RE = re.compile(r"^(?:<!--.*?-->\s*)+", flags=re.DOTALL)
COMMENT_BLOCK_RE = re.compile(r"<!--.*?-->", flags=re.DOTALL)
UNCLOSED_COMMENT_RE = re.compile(r"<!--.*", flags=re.DOTALL)


def clean_wikitext(
    text,
    *,
    normalize=DEFAULT_NORMALIZE,
    collapse=DEFAULT_COLLAPSE,
    keep_template_params=DEFAULT_KEEP_TEMPLATE_PARAMS,
    skip_style_tags=DEFAULT_SKIP_STYLE_TAGS,
):
    """
    Clean raw wikitext into plain text using mwparserfromhell.

    This follows mwparserfromhell's recommended high-level workflow:

    1. Parse source wikitext into a Wikicode object.
    2. Use strip_code() to produce readable plain text.

    mwparserfromhell is a source parser, not a full MediaWiki renderer. It does
    not expand templates, so text generated by transclusion is intentionally not
    recovered here.

    `skip_style_tags` is exposed for malformed quote markup, but defaults to
    False because enabling it leaves normal bold/italic markers in common text.
    """
    if not text:
        return ""

    try:
        text = _remove_unwanted_raw_markup(text)
        wikicode = mwparserfromhell.parse(text, skip_style_tags=skip_style_tags)
        _remove_unwanted_nodes(wikicode)
        cleaned_text = _strip_sections(
            wikicode,
            normalize=normalize,
            collapse=collapse,
            keep_template_params=keep_template_params,
        )
        return cleaned_text.strip()
    except Exception as e:
        print(
            f"Warning: mwparserfromhell failed to parse text. Fallback to basic cleanup. Error: {e}",
            file=sys.stderr,
        )
        return _fallback_clean_wikitext(text)


def _remove_unwanted_raw_markup(text):
    text = COMMENT_BLOCK_RE.sub("", text)
    text = UNCLOSED_COMMENT_RE.sub("", text)
    text = MAGIC_WORD_RE.sub("", text)
    text = _remove_tables(text)
    text = _remove_templates(text)
    text = REF_RE.sub("", text)
    text = REF_TAG_RE.sub("", text)
    text = MALFORMED_REF_LINE_RE.sub("", text)
    text = REFERENCES_TAG_RE.sub("", text)
    text = _remove_infobox_lines(text)
    text = _remove_media_link_lines(text)
    text = _remove_malformed_thumbnail_lines(text)
    text = _remove_orphan_table_rows(text)
    return _remove_or_rewrite_wikilinks_by_namespace(text)


def _remove_infobox_lines(text):
    cleaned_lines = []
    dropping_infobox = False

    for line in text.splitlines(keepends=True):
        stripped = line.lstrip()
        lower = stripped.lower()
        if lower.startswith("{{infobox"):
            dropping_infobox = True
            continue

        if dropping_infobox:
            if stripped.startswith("}}"):
                dropping_infobox = False
            elif (
                stripped
                and not stripped.startswith("|")
                and not stripped.startswith("{{")
            ):
                dropping_infobox = False
                cleaned_lines.append(line)
            continue

        cleaned_lines.append(line)

    return "".join(cleaned_lines)


def _remove_media_link_lines(text):
    cleaned_lines = []
    for line in text.splitlines(keepends=True):
        stripped = line.lstrip(":;*# 	")
        if stripped.startswith("[["):
            content = stripped[2:]
            namespace, _ = _split_namespace(content)
            if (
                namespace in MEDIA_PREFIXES
                and _find_balanced_end(stripped, 0, "[[", "]]") is None
            ):
                continue
        cleaned_lines.append(line)
    return "".join(cleaned_lines)


def _remove_malformed_thumbnail_lines(text):
    cleaned_lines = []
    for line in text.splitlines(keepends=True):
        stripped = line.lstrip()
        if _has_malformed_thumbnail_fragment(line):
            continue
        if stripped.startswith("|thumb|") and "]]" in stripped:
            continue
        if stripped.startswith("thumb|"):
            continue
        cleaned_lines.append(line)
    return "".join(cleaned_lines)


def _has_malformed_thumbnail_fragment(line):
    lower = line.lower()
    thumb_index = lower.find("thumb|")
    if thumb_index < 0:
        return False
    link_index = line.find("[[")
    return link_index < 0 or thumb_index < link_index


def _remove_orphan_table_rows(text):
    cleaned_lines = []
    orphan_table_depth = 0

    for line in text.splitlines(keepends=True):
        stripped = line.lstrip()
        if _looks_like_table_body_line(stripped):
            orphan_table_depth += 1
            continue

        if orphan_table_depth:
            if stripped.startswith("|}"):
                orphan_table_depth = 0
                continue
            elif _looks_like_table_body_line(stripped):
                continue
            else:
                orphan_table_depth = 0

        cleaned_lines.append(line)

    return "".join(cleaned_lines)


def _looks_like_table_body_line(stripped):
    return (
        stripped.startswith("|-")
        or stripped.startswith("! ")
        or stripped.startswith("!style")
        or stripped.startswith("!width")
        or stripped.startswith("| style")
        or stripped.startswith("|style")
        or stripped.startswith("| colspan")
        or stripped.startswith("|colspan")
        or stripped.startswith("| rowspan")
        or stripped.startswith("|rowspan")
    )


def _remove_tables(text):
    lines = text.splitlines(keepends=True)
    cleaned_lines = []
    table_depth = 0

    for line in lines:
        table_marker = _table_marker(line)
        if table_marker == "start":
            table_depth += 1
            continue

        if table_depth:
            if table_marker == "end":
                table_depth = max(0, table_depth - 1)
            elif table_marker == "start":
                table_depth += 1
            continue

        cleaned_lines.append(line)

    return "".join(cleaned_lines)


def _table_marker(line):
    stripped = line.lstrip()
    stripped = stripped.lstrip(":;*#")
    stripped = stripped.lstrip()
    stripped = LEADING_COMMENT_RE.sub("", stripped).lstrip()
    if stripped.startswith("{|"):
        return "start"
    if "{|" in stripped and stripped.startswith("<onlyinclude>"):
        return "start"
    if _contains_inline_table_start(stripped):
        return "start"
    if stripped.startswith("|}"):
        return "end"
    return None


def _contains_inline_table_start(stripped):
    if "{|" not in stripped:
        return False
    before, after = stripped.split("{|", 1)
    if not after.lstrip().startswith(
        ("class", "style", "border", "cellpadding", "cellspacing", "sortable")
    ):
        return False
    return before.rstrip().endswith(("", " ", "\t", "}", ">", "."))


def _remove_templates(text):
    return _transform_balanced_constructs(
        text,
        open_token="{{",
        close_token="}}",
        transform=lambda content, original: "",
    )


def _remove_or_rewrite_wikilinks_by_namespace(text):
    def transform(content, original):
        if _has_media_options(content):
            return ""

        namespace, rest = _split_namespace(content)
        if namespace in MEDIA_PREFIXES:
            return ""
        if namespace in CATEGORY_PREFIXES and rest:
            return f"[[{rest.strip()}]]"
        return original

    return _transform_balanced_constructs(
        text,
        open_token="[[",
        close_token="]]",
        transform=transform,
    )


def _has_media_options(wikilink_content):
    content = str(wikilink_content).lower()
    return any(
        option in content
        for option in ("|thumb", "|thumbnail", "|nhỏ", "|frameless", "|upright")
    )


def _transform_balanced_constructs(text, *, open_token, close_token, transform):
    result = []
    index = 0

    while index < len(text):
        if not text.startswith(open_token, index):
            result.append(text[index])
            index += 1
            continue

        end = _find_balanced_end(text, index, open_token, close_token)
        if end is None:
            result.append(text[index])
            index += 1
            continue

        content_start = index + len(open_token)
        content_end = end - len(close_token)
        original = text[index:end]
        content = text[content_start:content_end]
        result.append(transform(content, original))
        index = end

    return "".join(result)


def _find_balanced_end(text, start, open_token, close_token):
    depth = 0
    index = start

    while index < len(text):
        if text.startswith(open_token, index):
            depth += 1
            index += len(open_token)
            continue

        if text.startswith(close_token, index):
            depth -= 1
            index += len(close_token)
            if depth == 0:
                return index
            continue

        index += 1

    return None


def _split_namespace(wikilink_content):
    if ":" not in wikilink_content:
        return _normalize_namespace_title(wikilink_content), ""

    namespace, rest = wikilink_content.split(":", 1)
    return _normalize_namespace_title(namespace), rest


def _remove_unwanted_nodes(wikicode):
    for section in wikicode.get_sections(
        flat=True, include_lead=True, include_headings=True
    ):
        _remove_media_links(section)
        _rewrite_category_links(section)
        _remove_tags(section)


def _remove_media_links(section):
    for wikilink in section.filter_wikilinks(recursive=True):
        if _has_namespace_prefix(wikilink.title, MEDIA_PREFIXES):
            _try_remove(section, wikilink)


def _rewrite_category_links(section):
    for wikilink in section.filter_wikilinks(recursive=True):
        title = str(wikilink.title).strip()
        if not _has_namespace_prefix(title, CATEGORY_PREFIXES) or ":" not in title:
            continue

        _, category_name = title.split(":", 1)
        wikilink.title = category_name.strip()
        wikilink.text = None


def _remove_tags(section):
    for tag in section.filter_tags(recursive=True):
        if str(tag.tag).strip().lower() in REMOVED_TAGS:
            _try_remove(section, tag)


def _try_remove(section, node):
    try:
        section.remove(node)
    except ValueError:
        pass


def _has_namespace_prefix(title, prefixes):
    title = _normalize_namespace_title(title)
    return any(title == prefix or title.startswith(f"{prefix}:") for prefix in prefixes)


def _normalize_namespace_title(title):
    title = str(title).strip().lower().replace("_", " ")
    if ":" in title:
        namespace, rest = title.split(":", 1)
        return f"{namespace.strip()}:{rest.lstrip()}"
    return title


def _strip_sections(wikicode, *, normalize, collapse, keep_template_params):
    sections = []
    for section in wikicode.get_sections(
        flat=True, include_lead=True, include_headings=True
    ):
        cleaned_section = section.strip_code(
            normalize=normalize,
            collapse=collapse,
            keep_template_params=keep_template_params,
        ).strip()
        if cleaned_section:
            sections.append(cleaned_section)

    return "\n\n".join(sections)


def _fallback_clean_wikitext(text):
    try:
        wikicode = mwparserfromhell.parse(text)
        return wikicode.strip_code(
            normalize=DEFAULT_NORMALIZE,
            collapse=DEFAULT_COLLAPSE,
            keep_template_params=DEFAULT_KEEP_TEMPLATE_PARAMS,
        ).strip()
    except Exception:
        return text.strip()
